### ISSUE TITLE
Source file

### ISSUE THREAD

**Issue by DStang** [arundasan91/MPI---Message-Passing-Interface#1]
Hey, would you mind uploading the python source file? That would be awesome.

**Comment by arundasan91** [comment]
Hi @DStang , Are you looking for the image-scatter example? I've added a section in that document where you can copy paste the entire code at once: https://github.com/arundasan91/MPI---Message-Passing-Interface/blob/master/Image-Scatter-Gather-Tutorial.md#complete-code

**Comment by DStang** [comment]
Yes, that's what I was looking for. Thanks!
